discord_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import  static
from django.conf import settings
from discord_bot import views

app_name = 'discord_bot'

# from django.contrib import admin
# from django.urls import path, include
# from django.conf.urls.static import  static
# from django.conf import settings
# from portfolio import views


urlpatterns = [
    ## кавычки пустые, потому что, это домашная страница
    ## то есть самая первая
    path('', views.all_discord_bots, name='all_discord_bots'),
    path('all_discord_bots', views.all_discord_bots, name='all_discord_bots'),
    path('<int:discord_id>', views.detail, name='detail'),
]


# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import  static
from django.conf import settings
from portfolio import views




urlpatterns = [
    path('admin/', admin.site.urls),
    ## кавычки пустые, потому что, это домашная страница
    ## то есть самая первая
    path('', views.home, name='home'),
    path('discord_bot/', include('discord_bot.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discord_bot/models.py
from django.db import models

class Discord_bot(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to="discord_bot/images", default="C:/Users/constantion/Downloads/Telegram Desktop/photo_2022-01-13_08-56-10.jpg")
    # image = ResizedImageField (upload_to="discord_bot/images", blank=True, null=True)
    url = models.URLField(blank=True)
    link = models.URLField(blank=True)

    def __str__(self):
        return self.title


# Create your models here.

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to="portfolio/images")
    url = models.URLField(blank=True)


    #### возращает имя в панели админа
    def __str__(self):
        return self.title


# Create your models here.

discord_bot/views.py
from django.shortcuts import render, get_object_or_404
from .models import Discord_bot

def all_discord_bots(request):

    # discord_bot_count =  Discord_bot.objects.count
    discord_bots = Discord_bot.objects.order_by('-date')
    return render(request, 'discord_bot/all_discord_bots.html', {'discord_bots':discord_bots})


def detail(request, discord_id):
    discord_bot = get_object_or_404(Discord_bot, pk=discord_id)
    return render(request, 'discord_bot/detail.html', {'discord_bot':discord_bot})

# Create your views here.

portfolio/views.py
from django.shortcuts import render
from .models import Project

## функция для домашней страницы
def home (request):
    ## DJANGO Импортирует все данные из базы данных
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})



# Create your views here.

discord_bot/templates/discord_bot/all_discord_bots.html
{% extends 'portfolio/base.html' %}

{% block content %}





<div class ="container text-center">
<h1>Discord Bots</h1>
    {# Автоматически меняет количество в заголовке количество ботов, если один   #}
    {# То Bot, если много то Bots   #}
    <h2>Sabyr created {{ discord_bots.count }} bot{{ discord_bots.count|pluralize }}</h2>

    {% for discord_bot in discord_bots %}

        <a href = "{% url 'discord_bot:detail' discord_bot.id %}">
            <br>
            <h2> {{ discord_bot.title }}</h2></a>
        <a href="{{ discord_bot.url }}">
        <img src =" {{ discord_bot.image.url }}">
        <p></p>
{#        <h5 class="text-danger">{{ discord_bot.date|date:'MMM d Y '|upper }}</h5>#}
        <h4>{{ discord_bot.description|striptags|truncatechars:50 }}</h4>
    {% endfor %}

<br>
<a href = "{% url 'home' %}" class="btn btn-success btn-lg">Home</a>
<p>
{% endblock %}

discord_bot/templates/discord_bot/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ discord_bot.title }} </h1>


{#<h2>{{ discord_bot.date|date:'F jS Y' }}</h2>#}
<br>
    <h4>{{ discord_bot.description|safe }}</h4>

    <div class ="container text-center">
<a href="{{ discord_bot.link }}" class="btn btn-success btn-lg">Add bot</a>
        <div class="row justify-content-center my-3">
            <div
                    class="col-5">
    <img src =" {{ discord_bot.image.url }}" class="img-fluid" =>
                  </div>
        </div>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/logo123.png" %}">

  <title>Nurgaliyev Sabyr</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/logo123.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Sabyr's logo">
        <span>Nurgaliyev Sabyr</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/sabyr-nurgaliyev-43b4a822a/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://api.whatsapp.com/send?phone=77758712440&text=%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%B9%20%D0%B4%D0%B5%D0%BD%D1%8C%2C%20%D1%8F%20%D0%BF%D0%BE%20%D0%BF%D0%BE%D0%B2%D0%BE%D0%B4%D1%83..." target="_blank">WhatsApp Web</a>
          </li>
          <li>
            <a role="button" href="{% url 'discord_bot:all_discord_bots' %}" class="btn btn-primary">Discord_Bots</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sabyr.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">I'm a Python Developer, from Kazakhstan, Almaty 😉</h1>
  </div>
</div>

<h2 class="mt-5">Projects</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
    <a href = "{% url 'discord_bot:all_discord_bots' %}">Discord Bots</a>
  </div>
  {% endfor %}
</div>

{% endblock %}